- hosts: FRONTEND
  become: yes
  roles:
    - "frontend-p"

- hosts: MONGODB
  become: yes
  roles:
    - "mongodb-p"

- hosts: CATALOGUE
  become: yes
  roles:
    - "catalogue-p"

- hosts: REDIS
  become: yes
  roles:
    - "redis-p"

- hosts: USER
  become: yes
  roles:
    - "user-p"

- hosts: CART
  become: yes
  roles:
    - "cart-p"

- hosts: MYSQL
  become: yes
  roles:
    - "mysql-p"

- hosts: SHIPPING
  become: yes
  roles:
    - "shipping-p"

- hosts: RABBITMQ
  become: yes
  roles:
    - "rabbitmq-p"

- hosts: PAYMENT
  become: yes
  roles:
    - "payment-p"

- hosts: DISPATCH
  become: yes
  roles:
    - "dispatch-p"

