- name: Download {{ COMPONENT }} content
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp/{{ COMPONENT }}-main

- name: Remove {{ COMPONENT }} content
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Extract {{ COMPONENT }} content
  ansible.builtin.unarchive:
    src: /tmp/{{ COMPONENT }}-main
    dest: /tmp
    remote_src: yes