- name: Download {{ COMPONENT }} content
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp/{{ COMPONENT }}.zip

- name: Remove {{ COMPONENT }} content
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Create app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: Extract {{ COMPONENT }} content
  ansible.builtin.unarchive:
    src: /tmp/{{ COMPONENT }}.zip
    dest: /tmp
    remote_src: yes

