
- name: Remove old {{ COMPONENT }} content
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Create {{ COMPONENT }} content
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: Download and Extract {{ COMPONENT }} content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy {{ COMPONENT }} code
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/{{SUFFIX}}
    dest: "{{ APP_LOCATION }}"










#- name: Create app content
#  ansible.builtin.file:
#    path: "{{ APP_LOCATION }}"
#    state: directory
#
#- name: Download and Extract {{ COMPONENT }} content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: Copy {{ COMPONENT }} code
#  ansible.builtin.copy:
#    src: /tmp/{{ COMPONENT }}-main/{{SUFFIX}}
#    dest: "{{ APP_LOCATION }}"
#    remote_src: yes

