- name: Set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: Install pip modules for aws secret manager lookup
  ansible.builtin.pip:
    name:
      - botocore
      - boto3
    executable: pip3